import Notifications from "./Home/@Notifications/page";
import TansackProvider from "./Components/Providers/QueryProvider";
import "./globals.css";
import { Toaster, toast } from "sonner";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
type Types = {
  children: React.ReactNode;
};
export default function RootLayout({ children }: Types) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        {" "}
        <Toaster richColors />
        <TansackProvider> {children}</TansackProvider>
      </body>
    </html>
  );
}
