import Notifications from "./Home/@Notifications/page";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
type Types = {
  children: React.ReactNode;
};
export default function RootLayout({ children }: Types) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
